test

diff --git a/packages/app-rn/patches/react-native+0.69.5.patch b/packages/app-rn/patches/react-native+0.69.5.patch
--- a/packages/app-rn/patches/react-native+0.69.5.patch
+++ b/packages/app-rn/patches/react-native+0.69.5.patch
@@ -6,7 +6,7 @@ index 0000000..361f5fb
 @@ -0,0 +1 @@
 +export RCT_METRO_PORT=8081
 diff --git a/node_modules/react-native/scripts/react-native-xcode.sh b/node_modules/react-native/scripts/react-native-xcode.sh
-index 6f95a29..475bece 100755
+index 6f95a29..b521446 100755
 --- a/node_modules/react-native/scripts/react-native-xcode.sh
 +++ b/node_modules/react-native/scripts/react-native-xcode.sh
 @@ -27,34 +27,36 @@ if [[ "$CONFIGURATION" = *Debug* && ! "$PLATFORM_NAME" == *simulator ]]; then
@@ -138,3 +138,17 @@ index 6f95a29..475bece 100755
  
  if [[ $USE_HERMES != true ]]; then
    cp "$BUNDLE_FILE" "$DEST/"
+@@ -180,8 +196,8 @@ else
+   BUNDLE_FILE="$DEST/main.jsbundle"
+ fi
+ 
+-if [[ $DEV != true && ! -f "$BUNDLE_FILE" ]]; then
+-  echo "error: File $BUNDLE_FILE does not exist. This must be a bug with" >&2
+-  echo "React Native, please report it here: https://github.com/facebook/react-native/issues"
+-  exit 2
+-fi
++# if [[ $DEV != true && ! -f "$BUNDLE_FILE" ]]; then
++#   echo "error: File $BUNDLE_FILE does not exist. This must be a bug with" >&2
++#   echo "React Native, please report it here: https://github.com/facebook/react-native/issues"
++#   exit 2
++# fi
